//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_students
    {
        public int class_session_code { get; set; }
        public int student_id { get; set; }
        public string student_name { get; set; }
        public string attendee_id { get; set; }
        public string attendee_url { get; set; }
        public string email { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string stream { get; set; }
        public string pno { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public int duration { get; set; }
        public string startingtimestamp { get; set; }
        public string endingtimestamp { get; set; }
        public int status { get; set; }
        public System.Guid ssma_rowid { get; set; }
    }
}
