//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_students
    {
        public int class_session_code { get; set; }
        public int student_id { get; set; }
        public string student_name { get; set; }
        public string attendee_id { get; set; }
        public string attendee_url { get; set; }
        public string email { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string stream { get; set; }
        public string pno { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public int duration { get; set; }
        public string startingtimestamp { get; set; }
        public string endingtimestamp { get; set; }
        public int status { get; set; }
    }
}
