//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_details
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string company_name { get; set; }
        public string description { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string pno { get; set; }
        public string address { get; set; }
        public string password { get; set; }
    }
}
