//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class content
    {
        public int contentid { get; set; }
        public string filename { get; set; }
        public string subject { get; set; }
        public string description { get; set; }
        public System.DateTime upload_date { get; set; }
        public int uploadedby { get; set; }
        public int status { get; set; }
    }
}
