//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class content
    {
        public int contentid { get; set; }
        public string filename { get; set; }
        public string subject { get; set; }
        public string description { get; set; }
        public System.DateTime upload_date { get; set; }
        public int uploadedby { get; set; }
        public int status { get; set; }
    }
}
