//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_us
    {
        public int id { get; set; }
        public string email_address { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string message { get; set; }
        public int status { get; set; }
    }
}
