//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cours
    {
        public int course_id { get; set; }
        public string course_name { get; set; }
        public string course_code { get; set; }
        public int subject_id { get; set; }
        public int topic_id { get; set; }
        public string description { get; set; }
        public decimal price { get; set; }
        public Nullable<int> status { get; set; }
    }
}
