//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_price
    {
        public int price_id { get; set; }
        public int grade_id { get; set; }
        public int price_per_hour { get; set; }
        public int status { get; set; }
    }
}
