//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class courses_sort_order
    {
        public int course_order_id { get; set; }
        public int course_id { get; set; }
        public int sort_order { get; set; }
        public int status { get; set; }
    }
}
