//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interview_schedules
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime date { get; set; }
        public string time { get; set; }
        public string message { get; set; }
        public int isAccepted { get; set; }
        public int mode { get; set; }
        public int class_session_code { get; set; }
        public int status { get; set; }
    }
}
