//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interview
    {
        public int interview_id { get; set; }
        public string class_session_code { get; set; }
        public string class_title { get; set; }
        public int manager_id { get; set; }
        public string message { get; set; }
        public System.DateTime date { get; set; }
        public string time { get; set; }
        public int total_users { get; set; }
        public int duration { get; set; }
        public Nullable<int> client_id { get; set; }
        public string client_name { get; set; }
        public string client_url { get; set; }
        public string recording_url { get; set; }
        public int session_status { get; set; }
        public string startingtimestamp { get; set; }
        public string endingtimestamp { get; set; }
    }
}
