//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interview_schedules
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime date { get; set; }
        public string time { get; set; }
        public string message { get; set; }
        public int isAccepted { get; set; }
        public int mode { get; set; }
        public int class_session_code { get; set; }
        public int status { get; set; }
    }
}
