//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interviews
    {
        public int interview_id { get; set; }
        public string class_session_code { get; set; }
        public string class_title { get; set; }
        public int manager_id { get; set; }
        public string message { get; set; }
        public System.DateTime date { get; set; }
        public string time { get; set; }
        public int total_users { get; set; }
        public int duration { get; set; }
        public Nullable<int> client_id { get; set; }
        public string client_name { get; set; }
        public string client_url { get; set; }
        public string recording_url { get; set; }
        public int session_status { get; set; }
        public string startingtimestamp { get; set; }
        public string endingtimestamp { get; set; }
    }
}
