//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapping_subjects
    {
        public int id { get; set; }
        public int mapping_id { get; set; }
        public int subject_id { get; set; }
        public int isChecked { get; set; }
    }
}
