//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSSsmaDmTables
    {
        public int object_id { get; set; }
        public int schema_id { get; set; }
        public Nullable<byte> status { get; set; }
        public System.DateTime dm_start_time { get; set; }
    }
}
