//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSSsmaDmNCKeyColumns
    {
        public int object_id { get; set; }
        public string key_name { get; set; }
        public string key_type { get; set; }
        public int key_column_id { get; set; }
        public Nullable<int> index_column_id { get; set; }
        public Nullable<bool> is_disabled { get; set; }
        public Nullable<int> referenced_object_id { get; set; }
        public Nullable<byte> delete_referential_action { get; set; }
        public Nullable<byte> update_referential_action { get; set; }
        public Nullable<bool> is_not_for_replication { get; set; }
        public Nullable<bool> is_not_trusted { get; set; }
        public Nullable<int> referenced_column_id { get; set; }
    }
}
