//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_days
    {
        public int order_daysid { get; set; }
        public int order_id { get; set; }
        public int day_id { get; set; }
        public System.TimeSpan from_time { get; set; }
        public System.TimeSpan to_time { get; set; }
        public int status { get; set; }
    }
}
