//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_log
    {
        public int payment_id { get; set; }
        public int course_id { get; set; }
        public int user_id { get; set; }
        public float amount { get; set; }
        public string txn_id { get; set; }
        public int payment_status { get; set; }
        public System.DateTime datetime { get; set; }
    }
}
