//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile
    {
        public int profile_id { get; set; }
        public string pic { get; set; }
        public string name { get; set; }
        public string detail { get; set; }
        public string linked_url { get; set; }
        public int status { get; set; }
    }
}
