//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile
    {
        public int profile_id { get; set; }
        public string pic { get; set; }
        public string name { get; set; }
        public string detail { get; set; }
        public string linked_url { get; set; }
        public int status { get; set; }
    }
}
