//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_orders
    {
        public int order_id { get; set; }
        public int user_id { get; set; }
        public int amount { get; set; }
        public int totalhours { get; set; }
        public System.DateTime datetime { get; set; }
        public int grade_id { get; set; }
        public int board_id { get; set; }
        public int txnid { get; set; }
        public int payment_status { get; set; }
        public int payment_type { get; set; }
        public int status { get; set; }
    }
}
