//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_subject_details
    {
        public int sub_id { get; set; }
        public int user_id { get; set; }
        public string subject { get; set; }
        public string code { get; set; }
        public int teacher_assigned { get; set; }
        public float attendence { get; set; }
    }
}
