//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_details
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string email { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string stream { get; set; }
        public string pno { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string subjects { get; set; }
        public string college { get; set; }
        public string convenient_time { get; set; }
        public string password { get; set; }
        public string cv { get; set; }
        public int specialization { get; set; }
        public string total_exp { get; set; }
        public string brief { get; set; }
        public string pic { get; set; }
        public string up { get; set; }
    }
}
