//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class success_story_category
    {
        public int story_category_id { get; set; }
        public int success_story_id { get; set; }
        public int category_id { get; set; }
        public int status { get; set; }
    }
}
