//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class success_story
    {
        public int success_story_id { get; set; }
        public string user_name { get; set; }
        public string pic { get; set; }
        public Nullable<int> sort_number { get; set; }
        [DataType(DataType.MultilineText)]
        public string brief { get; set; }
        [DataType(DataType.MultilineText)]
        public string detail_description { get; set; }
        public int status { get; set; }
    }
}
