//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher_details
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string mobileno { get; set; }
        public string address { get; set; }
        public int age { get; set; }
        public string education { get; set; }
        public string grade { get; set; }
        public string subject { get; set; }
        public string details { get; set; }
        public string email { get; set; }
    }
}
