//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher_subject_details
    {
        public int quali_id { get; set; }
        public int user_id { get; set; }
        public string subjects { get; set; }
        public float attendence { get; set; }
    }
}
