//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teammembers
    {
        public int teammember_id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string designation { get; set; }
        public string company { get; set; }
        public string brief { get; set; }
        public string linkedinprofile { get; set; }
        public string mobile { get; set; }
        public string phone { get; set; }
        public int status { get; set; }
    }
}
