//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teammember
    {
        public int teammember_id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string designation { get; set; }
        public string company { get; set; }
        public string brief { get; set; }
        public string linkedinprofile { get; set; }
        public string mobile { get; set; }
        public string phone { get; set; }
        public int status { get; set; }
    }
}
