//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_attempts
    {
        public int attemptid { get; set; }
        public int userid { get; set; }
        public string session_id { get; set; }
        public int testid { get; set; }
        public System.DateTime datetime { get; set; }
        public int score { get; set; }
        public int status { get; set; }
    }
}
