//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public int testid { get; set; }
        public int currentid { get; set; }
        public string testcode { get; set; }
        public string testname { get; set; }
        public string description { get; set; }
        public int subjectid { get; set; }
        public int topicid { get; set; }
        public System.DateTime datecreated { get; set; }
        public int ispublished { get; set; }
        public int status { get; set; }
    }
}
