//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_attempt_details
    {
        public int attemptdetailsid { get; set; }
        public int attemptid { get; set; }
        public int questionid { get; set; }
        public int answerid { get; set; }
        public int status { get; set; }
    }
}
