//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tests
    {
        public int testid { get; set; }
        public int currentid { get; set; }
        public string testcode { get; set; }
        public string testname { get; set; }
        public string description { get; set; }
        public int subjectid { get; set; }
        public int topicid { get; set; }
        public System.DateTime datecreated { get; set; }
        public int ispublished { get; set; }
        public int status { get; set; }
    }
}
