//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_pswd { get; set; }
        public string name { get; set; }
        public string email_address { get; set; }
        public string user_type { get; set; }
        public string status { get; set; }
        public int student_status { get; set; }
        public int isAuthenticated { get; set; }
        public int approved { get; set; }
        public System.DateTime created_on { get; set; }
        public System.DateTime updated_on { get; set; }
        public System.DateTime lastLoginAt { get; set; }
        public string fb_id { get; set; }
        public int signup_source { get; set; }
    }
}
