//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_emails
    {
        public int id { get; set; }
        public int emailid { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public int to_userid { get; set; }
        public int email_read { get; set; }
        public int status { get; set; }
        public System.DateTime datetime { get; set; }
    }
}
