//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_emails
    {
        public int id { get; set; }
        public int emailid { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public int to_userid { get; set; }
        public int email_read { get; set; }
        public int status { get; set; }
        public System.DateTime datetime { get; set; }
    }
}
