//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_pswd { get; set; }
        public string name { get; set; }
        public string email_address { get; set; }
        public string user_type { get; set; }
        public string status { get; set; }
        public int student_status { get; set; }
        public int isAuthenticated { get; set; }
        public int approved { get; set; }
        public System.DateTime created_on { get; set; }
        public System.DateTime updated_on { get; set; }
        public System.DateTime lastLoginAt { get; set; }
        public string fb_id { get; set; }
        public int signup_source { get; set; }
    }
}
