//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitor_enquiry
    {
        public int VisitorEnquiryID { get; set; }
        public string VisitorName { get; set; }
        public string visitor_mobile { get; set; }
        public string visitor_email { get; set; }
        public string visitor_enquiry1 { get; set; }
        public sbyte status { get; set; }
    }
}
