//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitor_enquiry
    {
        public int VisitorEnquiryID { get; set; }
        public string VisitorName { get; set; }
        public string visitor_mobile { get; set; }
        public string visitor_email { get; set; }
        public string visitor_enquiry1 { get; set; }
        public short status { get; set; }
        public System.Guid ssma_rowid { get; set; }
    }
}
